name: Danger Review

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v1
      - name: Danger Review
        uses: danger/danger-js@9.1.6
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}